// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv-J79sxPCh_TpbR_K0Xq7DuAAvtvcXoE',
    appId: '1:482268046781:web:ea7a80bb95c01523265ed4',
    messagingSenderId: '482268046781',
    projectId: 'nipponxjapondemo',
    authDomain: 'nipponxjapondemo.firebaseapp.com',
    storageBucket: 'nipponxjapondemo.appspot.com',
    measurementId: 'G-JL0FVESMLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIQLzLhDW-ZwqydSYl2xhSz9DFCVCCw4I',
    appId: '1:482268046781:android:ad436ff8fdab8119265ed4',
    messagingSenderId: '482268046781',
    projectId: 'nipponxjapondemo',
    storageBucket: 'nipponxjapondemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBak64-Tx7lJ3vNRpQs4zvcYGrmY0P0Qc0',
    appId: '1:482268046781:ios:3cae29f4a4e443ae265ed4',
    messagingSenderId: '482268046781',
    projectId: 'nipponxjapondemo',
    storageBucket: 'nipponxjapondemo.appspot.com',
    iosBundleId: 'com.example.proyectoTurismo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBak64-Tx7lJ3vNRpQs4zvcYGrmY0P0Qc0',
    appId: '1:482268046781:ios:3cae29f4a4e443ae265ed4',
    messagingSenderId: '482268046781',
    projectId: 'nipponxjapondemo',
    storageBucket: 'nipponxjapondemo.appspot.com',
    iosBundleId: 'com.example.proyectoTurismo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv-J79sxPCh_TpbR_K0Xq7DuAAvtvcXoE',
    appId: '1:482268046781:web:21ff09cd074e3486265ed4',
    messagingSenderId: '482268046781',
    projectId: 'nipponxjapondemo',
    authDomain: 'nipponxjapondemo.firebaseapp.com',
    storageBucket: 'nipponxjapondemo.appspot.com',
    measurementId: 'G-CXY55MP53G',
  );
}
